### ISSUE TITLE
Pruebas de Caja Negra

### ISSUE THREAD

**Issue by BordaDenisse** [LNicoF/Taggify#32]
La prueba de la caja negra intenta encontrar errores de las
siguientes categorías: 
1) funciones incorrectas o ausentes; 
2) errores de interfaz; 
3) errores en estructuras de datos o en acceso a bases de datos externas; 
4) errores de rendimiento 
5) errores de inicialización y terminación.

**Comment by LNicoF** [comment]
Las pruebas de caja negra no son un tipo especifico de pruebas
Unit testing e integration testing son pruebas de caja negra
